baseURL = "https://sglearning.netlify.app"
languageCode = 'en-gl.eus'
title = "Stuart Gibson | Interactive Learning & Design"
theme = "ananke"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
