baseURL = "https://sglearning.netlify.app"
languageCode = 'en-gl.eus'
title = "Stuart Gibson | Interactive Learning & Design"
theme = "ananke-local"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

[[menu.main]]
    name = "Project Lab"
    url = "/project-lab/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
